### ISSUE TITLE
libcrypto.so.1.0.0 error in cnv_facets. 

### ISSUE THREAD

**Issue by wangxlab** [dariober/cnv_facets#14]
Hi, 

I installed cnv_facets through bioconda and was testing it.  I think installation was okay, but I get error while running cnv_facets.   Please see the error message below.  It says "snp-pileup: error while loading shared libraries: libcrypto.so.1.0.0"  

I installed cnv_facets on supercomputer (Pittsburgh Supercomputing center, PSC). A PSC staff said that "libcrypto.so.1.0.0" is an old library and it was replaced by 'libcrypto.so.1.0.2k' during system upgrade. And, he said that "libcrypto.so.1.0.0" is not installable any more. I pasted his email at the bottom, after error message   

I wonder if you can change cnv_facets to use the new library, libcrypto.so.1.0.2k.  Or, do you have any advice for me to solve this problem? 

##########################################################
snp-pileup: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Error in checkForRemoteErrors(val) : one node produced an error: 
Error in computing snp pileup. Exit code 127 from execution of ./6713_3_2.csv.gz_191108-122923_6b7acb9f5bc/snp_pileup.1.sh
Calls: exec_snp_pileup_parallel ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

#################################################

taking the nodes to CentOS 7.6, which  may have cause some older libraries to get dropped (and which may not be possible to install). In fact, if you look in /usr/lib64/ there it is the newer version:

[gomez@r005 lib64]$ pwd
/usr/lib64
[gomez@r005 lib64]$ ls -l libcrypto*
lrwxrwxrwx 1 root root      19 Oct 23 12:27 libcrypto.so -> libcrypto.so.1.0.2k
lrwxrwxrwx 1 root root      19 Oct 23 12:23 libcrypto.so.10 -> libcrypto.so.1.0.2k
-rwxr-xr-x 1 root root 2516624 Mar 12  2019 libcrypto.so.1.0.2k
[gomez@r005 lib64]$

**Comment by dariober** [comment]
Hi- I'm not sure why this is happening. Can you try to install `cnv_facets` in its own environment? Like:

```
conda create -n env_cnv_facets
conda activate env_cnv_facets
conda install cnv_facets

# Run cnv_facets.R as required:
cnv_facets.R ...
```

If this works, try reinstalling samtools, bcftools and snp-pileup in your working environment (or just use the new `env_cnv_facets`)   

I'm not sure it matters, but make sure your conda channels are in the right order (see https://bioconda.github.io/user/install.html#set-up-channels) and you use the latest version of conda.

Let me know how you get on...

**Comment by wangxlab** [comment]
Hi, 

Thank you for your advice.   I removed cnv_facets and reinstalled.  I made sure the conda channels are in the right order and also I installed snp-pileup in the working environment. (I can't install samtools as it was already installed as a module in the supercomputer).   But, I got the same error message while running cnv_facets.  

I tried to install cnv_facets to another supercomputer in my university.   Strangely, this cnv_facets is working well without any error, although the new version of "libcrypto.so.1.0.2k" is installed like the Pittsburgh Supercomputing center (PSC).  So, I am using cnv_facets in the supercomputer in my university.  

Thank you for your help, though!
Sanghoon

**Comment by dariober** [comment]
>  I removed cnv_facets and reinstalled

Rather than removing and reinstalling, I would try creating a new conda environment as suggested in my previous post. In this way, you get a fresh installation of all the dependencies. By the way, I don't know how you are using conda, but in general is better to create a dedicated environment for each project you have and install there the dependencies.

**Comment by dariober** [comment]
Sorry about that and thanks for reporting the issue. The latest conda recipe should have this problem fixed. See https://github.com/bioconda/bioconda-recipes/pull/19969 for some explanation.
