### ISSUE TITLE
Running cnv_facets for tumor samples that don't have normal counterpart samples

### ISSUE THREAD

**Issue by LeiG1103** [dariober/cnv_facets#15]
Hi,

I am running cnv_facets for breast cancer cell lines but as we know cell lines don't have normal counterpart.  Therefore, I got normal breast whole exome sequencing (WXS) .BAM files from TCGA and running cnv_facets, and I could get output files. I wonder if you have experienced running cnv_facets for tumor samples (.bam) that don't have paired normal samples (.bam) and whether we can trust the result or not.  If you have any advice, could you give?  

Thank you, 
Lei

**Comment by dariober** [comment]
Hi- A normal sample is required, whether matched or unmatched. If you have an unmatched normal, you should use the `--unmatched` flag which is then passed to the facets function `preProcSample`. There was some discussion about using an unmatched normal here https://github.com/mskcc/facets/issues/41

About the reliability of the results, I cannot comment much. I also used an unmatched normal for some cell lines and, as I recall, the results where reasonable. But with cell lines I guess you can't tell whether the CNVs are tumour specific or they are the result of the proliferation of the tumour cells.

Hope this helps!
