### ISSUE TITLE
Germline CNV calling?

### ISSUE THREAD

**Issue by xysj1989** [dariober/cnv_facets#16]
Hello,

We only have Families based Whole Genome Sequencing data from germline blood samples.
Is it possible to use facets conduct germline CNV calling? 

Best regards.

**Comment by dariober** [comment]
Hi- I guess you could run your samples against an unmatched normal sample that doesn't contain CNVs. The unmatched normal could even be created by combining several normal samples. 

However, it may be better to use a CNV caller designed for germline calling, like [canvas](https://github.com/Illumina/canvas).
