### ISSUE TITLE
No circles in spider plot

### ISSUE THREAD

**Issue by ahwanpandey** [dariober/cnv_facets#2]
Hello,

Thanks for this tool!

I ran cnv_facets on some whole genome samples with your recommended values. None of the spider plots have circles in them.

```
cnv_facets.R \
     -t tumor.bam \
     -n normal.bam \
     -vcf common_all_20180423.vcf.gz \
     -o output \
     --gbuild hg19 \
     --cval 25 400 \
     --nbhd-snp 500 \
     --depth 25 4000 \
     --snp-nprocs 8 \
     --snp-baq 10 \
     --snp-mapq 5
```

I have attached all the plots generated.

Note: I have also run the tool with various combinations of cval [25 400] [25 1000] and [50 1000] and they all have the same problem.

![aocs-116-1-3 cval_25_400 nbhd-snp_500 cnv](https://user-images.githubusercontent.com/8450532/52254117-ea3cdd00-295f-11e9-9520-fa724357eb53.png)
[AOCS-116-1-3.cval_25_400.nbhd-snp_500.cov.pdf](https://github.com/dariober/cnv_facets/files/2830806/AOCS-116-1-3.cval_25_400.nbhd-snp_500.cov.pdf)
[AOCS-116-1-3.cval_25_400.nbhd-snp_500.spider.pdf](https://github.com/dariober/cnv_facets/files/2830807/AOCS-116-1-3.cval_25_400.nbhd-snp_500.spider.pdf)

Thanks!

**Comment by ahwanpandey** [comment]
Also, are there any other parameters you would recommend for WGS data to get cleaner segmentation? Most of my data is 40x Germline and 80x Tumor. I don't really want to loose small focal changes but just looking at the plot, it seems to be pretty noisy.

Thanks!

**Comment by ahwanpandey** [comment]
I loaded the pileup created by cnv_facets into the original FACETS R library and was successful in generating the circles in the spider plot. It's just cnv_facets not showing them for some reason.

![aocs-116-1-3 logrlogorspider](https://user-images.githubusercontent.com/8450532/52312954-bf569580-2a00-11e9-8d79-102336ffcdaf.png)

**Comment by dariober** [comment]
Hi- thanks for reporting this and apologies for the trouble. Could you post the version of cnv_facets from:

```
cnv_facets.R -v
```

Also it would be great if you could send me the csv pileup by putting it on e.g. dropbox so I can have a look and see if I can reporduce the bug. (To anonimise the data you can drop the REF and ALT columns with `gunzip -c my_pileup.csv.gz | cut -f 1,2,5,6,9,10 -d',' | gzip > my_pileup.x.csv.gz`).

The version of facets that is built in cnv_facets may not be the latest available. If that is the case I can rebuild cnv_facets with the latest one.

**Comment by ahwanpandey** [comment]
Hey Dario,

Thanks for the reply. Here is the version:

```
cnv_facets.R -v
0.12.1; facets=0.5.14
```

And the data is here:

https://www.dropbox.com/sh/xeou3ildyhiqcd6/AAADFy0tKwj_f1EkKAsj_mM8a?dl=0

Thanks!

**Comment by ahwanpandey** [comment]
I just manually updated FACETS:

```
cnv_facets.R -v
0.12.1; facets=0.6.0
```

Still the same issue, but the plot has a legend now.

[AOCS-116-1-3.cval_25_400.nbhd-snp_500.spider.pdf](https://github.com/dariober/cnv_facets/files/2838749/AOCS-116-1-3.cval_25_400.nbhd-snp_500.spider.pdf)

**Comment by dariober** [comment]
Indeed, this was an embarrassing bug now fixed (apologies). I'm going to upload version 0.13.0 to bioconda and it should be available there in a day or two.
