### ISSUE TITLE
Pooled multiple controls bam files together ?

### ISSUE THREAD

**Issue by npatel22526** [dariober/cnv_facets#20]
Hello, 

Thanks for the facets wrapper. We have 23 unmatched control bam files. I would like to utilize them as a single unmatched controls against tumor samples.  I can merge them together with samtools merge (or similar) but then the depth will be incomparable to tumor sample, and not sure how will allele frequencies will be impacted. Do you have suggestion on way to pool multiple samples together. Of course, I can choose the one sample to use as unmatched controls but then which one to choose will be an issues. 

Best, 
Nick

**Comment by carinogurjao** [comment]
I have the same question - any suggestion would be appreciated! And thanks for the nice wrapper :)

**Comment by lvzenglei** [comment]
I have the same question - any suggestion would be appreciated!

**Comment by dariober** [comment]
Apologies I never addressed this question. From top of my head, I would say that either choosing one representative control or merging all controls is going to throw away the information about the variability between controls. (The difference in depth between merged control tumour shouldn't be an issue). 

Ideally, I would compare each tumour against each control and then use some heuristics to select a trustworthy set of CNVs, for example by retaining CNV detected against at least xxx controls. But I understand this could be in itself quite a bit of work. It may be still be worth trying it to get a feel of the variability and to see if some controls are suspiciously unusual and should be discarded. After that, I would proceed with the merged approach.

Posting this question on the FACETS repository may give you better answers (`cnv_facets` is a wrapper, the real work is done by FACETS.)

**Comment by lvzenglei** [comment]
Thanks for your answer, I will have a try~
