### ISSUE TITLE
LCN_EM=. ?

### ISSUE THREAD

**Issue by wclee47** [dariober/cnv_facets#21]
Hi Dario, thanks for this program.
In the output, some segments have LCN_EM set to ".".
I think this might be different from the value "0".
Do you have any idea how to interpret the value "." in LCN_EM?

Appreciated!

**Comment by dariober** [comment]
Hi - LCN_EM="." means the value is missing (NA). As to the reason why it happened and how to interpret it, I can't tell for sure especially without seeing the data. It may be the region is hypersegmented. Maybe the discussions at https://github.com/mskcc/facets/issues/62 and https://github.com/mskcc/facets/issues/50 help? 

Keep in mind that cnv_facets is just a wrapper around the FACETS package so these sort of questions may be better answered by the developers of FACETS.

(Closing the issue now but feel to reopen)

Dario
