### ISSUE TITLE
--snp-vcf option

### ISSUE THREAD

**Issue by viancheng** [dariober/cnv_facets#23]
hi , I'm using cnv_facets.R script calling somatic CNV,
I want to make sure that file after --snp-vcf option is human common snp database( such as dbsnp), or the merged Polymorphic site of my own tumor and normal sample?

looking for reply~
viancheng

**Comment by dariober** [comment]
Hi- If I understand correctly your question, you are asking whether you should use a generic reference file of SNP, like dbSNP, or you should make your own SNP database based on your tumour and normal sample. The answer is that the generic SNP file (e,g from dbSNP) is fine. There may be some advantage in a custom made reference but I would keep it simple and use the common reference.

Hope this helps!
