### ISSUE TITLE
conda cnv_Facets does nbot work

### ISSUE THREAD

**Issue by 2236529177** [dariober/cnv_facets#30]
thanks  a  lot.
I am trying to install cnv_Facets in linux, but it does not work

 conda install cnv_facets --channel conda-forge --channel bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /

I also download the giihub file cnv_facets-master.zip, and install it in linux, but it say it is not a r packaeg.

can you give me some suggestions?

**Comment by dariober** [comment]
You are showing the output of conda until "Solving environment: /". Have you waited for it to complete or you terminated it yourself? If it completed with errors, please show the error messages.

**Comment by 2236529177** [comment]
I waited for a whole afternoon, no end.
I want to ask you anopther question, have you ever done tumor-only wgs on cnv-facets, can you share me youe parameter if you have ever done.
thanks a lot

**Comment by 2236529177** [comment]
conda install cnv_facets --channel conda-forge --channel bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.


errors like this
