### ISSUE TITLE
vcf file

### ISSUE THREAD

**Issue by sotaro-kanematsu** [dariober/cnv_facets#32]
Hi 
I would like to ask the genome version of output vcf file via cnv_facets.R (maybe named *.vcf).
I used snp vcf file named common_all_20170710.vcf.gz (hg19) as input, however, when I check the output vcf file, the reference
version was hg38.
Does cnv_facets convert genome version automatically?
or I do wrong something ?

**Comment by dariober** [comment]
Hi- The genome version in the vcf header is taken from the command line argument `--gbuild/-g` where the default is hg38. If you are working with hg19, you should use `cnv_facets.R --gbuild hg19 ...` 

Does it make sense? If not can you post the command line you used and perhaps the header of the VCF output?
