### ISSUE TITLE
Filtering VCF

### ISSUE THREAD

**Issue by ahwanpandey** [dariober/cnv_facets#4]
Hi Dario,

You mention in your usage page the following to filter for relevant CNVs

> CNLR_MEDIAN_CLUST
> USe this VCF tag to filter for records where the difference in read depth coverage between tumour and normal. The tag CNLR_MEDIAN should be well correlated with CNLR_MEDIAN_CLUST so using one or the other should not make much difference. Use the plot of CNV profile, log-ratio panel of <prefix>.cnv.png to decide on a sensible thresholds.
> 
> MAF_R_CLUST
> Use this VCF tag to filter for CNVs significant difference in tumour allele frequency. Use the plot of CNV profile, log-odds-ratio panel of <prefix>.cnv.png to decide on a sensible thresholds. As above MAF_R_CLUST is correlated with MAF_R.

Now when one has hundreds of samples its pretty time consuming to filter this way. Would it suffice to just filter for events that are not `SVTYPE=NEUTR`?

Thanks.

**Comment by dariober** [comment]
> Would it suffice to just filter for events that are not `SVTYPE=NEUTR`

Probably yes. I think one should optimize the parameters using, among other strategies, visual inspection in one or few samples. Once you are happy, you can filter out SVTYPE=NEUTR (consider also CNLR_MEDIAN_CLUST and TCN_EM and LCN_EM). But I'm quite hesitant in giving any strong recommendation.
