### ISSUE TITLE
error in evaluating the argument 'con' in selecting a method for function 'isOpen': TabixFile: file(s) do not exist:

### ISSUE THREAD

**Issue by asmlgkj** [dariober/cnv_facets#46]
thanks a lot for this great package, solid. can you have a lookof mine question?

conda install mamba 
mamba install cnv_facets
mamba install 'r-facets>=0.6.1' 'r-data.table' 'r-ggplot2' 'r-argparse>=2' 'snp-pileup>=0.6.1' 'r-gridextra' 'bioconductor-rsamtools' 'samtools' 'bcftools >=1.9' 
git clone https://github.com/dariober/cnv_facets.git   and get the cnv_facets.R

and use the Rscript in the absolute path of conda environment of cnv_facets

cnv_facets.R -t <tumour.bam> -n <normal.bam> -vcf <snps.vcf.gz> -o <output_prefix>
but gets an error

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'con' in selecting a method for function 'isOpen': TabixFile: file(s) do not exist:
  test.vcf.gz’
  ‘test.vcf.gz.tbi’
Calls: exec_snp_pileup_parallel ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by dariober** [comment]
Hi- Is your vcf file actually called `test.vcf.gz`? If so can you check if the argument `-vcf` is actually pointing to it? Maybe show the actual command you are executing.

**Comment by asmlgkj** [comment]
sorry, I misunderstand it as an output, so what kind of vcf it accepts, 
can vcf output by vardict it ?

**Comment by dariober** [comment]
Have a look at the [documentation](https://github.com/dariober/cnv_facets#option-1-bam--vcf-input) (admittedly quite terse). Basically, this is a vcf file of common polymorphic SNPs.Note also that `cnv_facets.R` is a command line wrapper for the R package [facets](https://github.com/mskcc/facets). For more detail of the method look at the R package itself and its pubblication. I'm closing the issue now but feel free to re-open.

**Comment by asmlgkj** [comment]
@dariober 
thanks a lot. another errors wanted for help. the same as above, but a vcf from NCBI
Rscript cnv_facets/bin/cnv_facets.R -t   test1_CASE.sort_dedup.bam -n test1_.sort_dedup.bam -vcf human_9606_b151_GRCh37p13/00-common_all.vcf.gz -o test1_
Error in makeCluster(nprocs, type = "FORK") : 
  could not find function "makeCluster"
Calls: exec_snp_pileup_parallel
Execution halted
