### ISSUE TITLE
when input bam , nedd to remove or mark duplicates filres?

### ISSUE THREAD

**Issue by YangLeng90** [dariober/cnv_facets#48]
when input bam , Does it need to remove or mark duplicates first?

**Comment by dariober** [comment]
Hi- Marking duplicates is not a requirement, but in most cases it is preferable to mark them. [snp-pileup](https://github.com/mskcc/facets/blob/master/inst/extcode/snp-pileup.cpp#L105), one of the tools behind cnv_facets will ignore reads marked as duplicate. 

I close the issue now but feel free to re-open.
