### ISSUE TITLE
question about ploidy estimate

### ISSUE THREAD

**Issue by guillaume-rs** [dariober/cnv_facets#54]
Hi,
I've used CNV_facets on multiple WES samples. For some of them I get a high estimated ploidy (around 4).
To my understanding it can correspond to whole genome duplication event, or an error in the estimated ploidy and average diploid state.
Here is an example of such results :

![image](https://github.com/dariober/cnv_facets/assets/26896372/e6ba7c06-3e3a-469a-92e8-6816d745f786)

I'm not used to interpret CNV genomic profile and I'm not sure to what extend this result is relevant.
Does it look like an obvious mistake from FACETS or could it be indeed due to a duplication event?

Many thanks,
Guillaume

**Comment by dariober** [comment]
Hi Guillaume - I can't tell, really. I have to say that I haven't looked a CNVs for quite a while even if I'm happy to maintain the `cnv_facets` package. Try posting this on the FACETS repository where the developer(s) may have a better view. (Remember that `cnv_facets` is just a convenient wrapper around the FACETS R package)

**Comment by guillaume-rs** [comment]
Hi Dario,
Thank you very much for your quick feedback.
I will ask this on the FACETS repository.
