### ISSUE TITLE
Do I need to set "--target" option for exome data?

### ISSUE THREAD

**Issue by jeffchen2000** [dariober/cnv_facets#56]
Dear Dariober
I have exome data, (say from SureSelect probe), should I set "--target" option like this:
"--target SureSelect_probe.bed"

or if you can provide a recommended/example of full command for exome data will be very help!
thanks
Jeff C

**Comment by dariober** [comment]
Hi- Yes, `--target SureSelect_probe.bed` is what I would do. E.g.:

```
cnv_facets.R --target SureSelect_probe.bed -t <tumour.bam> -n <normal.bam> -vcf <snps.vcf.gz> -o <output_prefix>
```

as for other use cases, you may need to tweak some analysis parameters to improve results (see the README and the documentation of the FACETS package).
