### ISSUE TITLE
Which vcf file should be used?

### ISSUE THREAD

**Issue by h170607** [dariober/cnv_facets#58]
Hi, 
I read the web https://www.ncbi.nlm.nih.gov/variation/docs/human_variation_vcf/, and am not sure which vcf file should be used.
Can the vcf parameter use other databases? Can tbi files be generated with tools like tabix or bcftools etc?

**Comment by dariober** [comment]
Hi- As noted in the [README](https://github.com/dariober/cnv_facets#option-1-bam--vcf-input), [common_all.vcf.gz](https://www.ncbi.nlm.nih.gov/variation/docs/human_variation_vcf/) is generally a good choice. And yes you can use any vcf file with SNPs you think are more appropriate to your use case. Google vcf + tbi to see how to generate them. Assuming your file is already sorted but not compressed, something like this should do:

```
bgzip in.vcf
tabix -p in.vcf.gz
```
