### ISSUE TITLE
(CNLR_MEDIAN) or (CNLR_MEDIAN - dipLogR)

### ISSUE THREAD

**Issue by ahwanpandey** [dariober/cnv_facets#6]
Hi again,

I was wondering what the correct value to use is for the log-ratio of a segment. I believe the tcn and lcn values have been corrected for ploidy and purity but logR values are not?

These log ratio values would be used for segment data visualization in IGV as well as for GISTIC analyses, and perhaps also to assign a log-ratio value to a gene.

Thanks!

**Comment by dariober** [comment]
I think (CNLR_MEDIAN - dipLogR) is usually more meaningful. About ploidy correction see https://github.com/mskcc/facets/issues/73

**Comment by ahwanpandey** [comment]
Thank you for the directions!
