### ISSUE TITLE
Warning message: region "1" specifies an unknown reference name. Continue anyway.

### ISSUE THREAD

**Issue by thebrownlife** [dariober/cnv_facets#60]
I have the bam files of a tumour sample "T11QM0022" and its matched normal sample "B11QM0022". They were generated using the GATK4 Best Practices pipeline. They are sorted and index. However, when I run the cnv_facets command on these bam files, I get the following messages on my Linux terminal.

`[main_samview] region "1" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "1" specifies an unknown reference name. Continue anyway.
Finished in 1.590000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "2" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "2" specifies an unknown reference name. Continue anyway.
Finished in 1.680000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "3" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "3" specifies an unknown reference name. Continue anyway.
Finished in 1.640000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "4" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "4" specifies an unknown reference name. Continue anyway.
Finished in 1.530000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "5" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "5" specifies an unknown reference name. Continue anyway.
Finished in 1.430000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "6" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "6" specifies an unknown reference name. Continue anyway.
Finished in 1.400000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "7" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "7" specifies an unknown reference name. Continue anyway.
Finished in 1.310000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "8" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "8" specifies an unknown reference name. Continue anyway.
Finished in 1.310000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "9" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "9" specifies an unknown reference name. Continue anyway.
Finished in 0.990000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "10" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "10" specifies an unknown reference name. Continue anyway.
Finished in 1.130000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "11" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "11" specifies an unknown reference name. Continue anyway.
Finished in 1.140000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "12" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "12" specifies an unknown reference name. Continue anyway.
Finished in 1.090000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "13" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "13" specifies an unknown reference name. Continue anyway.
Finished in 0.900000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "14" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "14" specifies an unknown reference name. Continue anyway.
Finished in 0.750000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "15" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "15" specifies an unknown reference name. Continue anyway.
Finished in 0.770000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "16" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "16" specifies an unknown reference name. Continue anyway.
Finished in 0.880000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "17" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "17" specifies an unknown reference name. Continue anyway.
Finished in 0.680000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "18" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "18" specifies an unknown reference name. Continue anyway.
Finished in 0.880000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "19" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "19" specifies an unknown reference name. Continue anyway.
Finished in 0.570000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "20" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "20" specifies an unknown reference name. Continue anyway.
Finished in 0.500000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "21" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "21" specifies an unknown reference name. Continue anyway.
Finished in 0.380000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "22" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "22" specifies an unknown reference name. Continue anyway.
Finished in 0.350000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "X" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "X" specifies an unknown reference name. Continue anyway.
Finished in 0.970000 seconds.
[W::hts_idx_load2] The index file is older than the data file: B11QM0022.recal.bai
[main_samview] region "Y" specifies an unknown reference name. Continue anyway.
[W::hts_idx_load2] The index file is older than the data file: T11QM0022.recal.bai
[main_samview] region "Y" specifies an unknown reference name. Continue anyway.
Finished in 0.020000 seconds.
[2024-04-16 16:28:22] Loading file T11QM0022.csv.gz...
[2024-04-16 16:28:23] Analysis stopped: pileup file T11QM0022.csv.gz has no records`

Can someone please explain the chromosomes have unknown reference name? Thank you!

**Comment by dariober** [comment]
> The index file is older than the data file

Can you make sure the indexes are up-to-date with the bam files? In doubt, you can recreate them with:

```
samtools index tumor.bam
samtools index normal.bam
```

**Comment by thebrownlife** [comment]
Hi Dario, 
Thanks for your suggestion. I reindexed the bam files but the same error of "region "1" specifies an unknown reference name. Continue anyway." is still showing up. Any idea what may be causing it?

**Comment by JuleBrenningmeyer** [comment]
Hi,

I have the same error message. Have you found a solution?

**Comment by ankashchenko** [comment]
Hello! I faced with this problem when I used .vcf file with common SNPs from ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/ as was recommended here https://github.com/mskcc/facets/issues/66. Chromosomes are labeled only by their number in this vcf file (1, 2, etc in CHROM column), whereas in my .bam files the labeling is chr1, chr2, etc. Therefore I got such error. 

I simply used bcftools and additional .txt file to rename chromosomes in vcf:
bcftools annotate --rename-chrs names.txt input.vcf.gz -O z -o output.vcf.gz

You can manually create names.txt. The example of such file:
1 chr1
2 chr2
3 chr3
4 chr4
5 chr5
6 chr6

After renaming I did not get this error anymore. So, just in case, check the labeling in your .bam and .vcf

**Comment by thebrownlife** [comment]
@ankashchenko thanks for posting the solution!

**Comment by dariober** [comment]
I'm closing this issue since it seems due to mismatching names between vcf and bam files and this is not related to cnv_facets. Feel free to comment & reopen though.
