### ISSUE TITLE
Issue after installing with conda

### ISSUE THREAD

**Issue by danielt86** [dariober/cnv_facets#61]
I recently installed cnv_facets with the following instructions in my University's HPC cluster:
mamba create -n my_project
mamba activate my_project
mamba install -c bioconda -c conda-forge cnv_facets

The installation works just fine, however when I try running the script i get this error:

error: This is R 3.6.3 but data.table has been installed using R 4.4.1. The major version must match. Please reinstall data.table.

I also tried installing in a new environment using both options in this site:
https://anaconda.org/bioconda/cnv_facets

And I still get the same error. As if the installation is somehow forcing data.table to be installed using R 4.4.1 (I have no clue how it does it). 
Any ideas? or what am I doing wrong here?
Thanks!

**Comment by dariober** [comment]
Hi- can you post the output of  `mamba list -n my_project`? Mine created just now is below and it seems to work fine.

Note that the version of data.table I get is 1.14. Perhaps try to install it manually with:

```
mamba install --freeze-installed -n my_project 'r-data.table=1.14.0'
```

```
mamba list -n my_project
# packages in environment at /home/dario/miniforge3/envs/my_project:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   h69a702a_16    conda-forge
bcftools                  1.9                  h68d8f2e_9    bioconda
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_33    conda-forge
bioconductor-biobase      2.46.0            r36h516909a_0    bioconda
bioconductor-biocgenerics 0.32.0                    r36_0    bioconda
bioconductor-biocparallel 1.20.0            r36he1b5a44_0    bioconda
bioconductor-biostrings   2.54.0            r36h516909a_0    bioconda
bioconductor-delayedarray 0.12.0            r36h516909a_0    bioconda
bioconductor-genomeinfodb 1.22.0                    r36_0    bioconda
bioconductor-genomeinfodbdata 1.2.2                     r36_0    bioconda
bioconductor-genomicalignments 1.22.0            r36h516909a_0    bioconda
bioconductor-genomicranges 1.38.0            r36h516909a_0    bioconda
bioconductor-iranges      2.20.0            r36h516909a_0    bioconda
bioconductor-rhtslib      1.18.0            r36hdb70ac9_1    bioconda
bioconductor-rsamtools    2.2.0             r36he1b5a44_0    bioconda
bioconductor-rtracklayer  1.46.0            r36h516909a_0    bioconda
bioconductor-s4vectors    0.24.0            r36h516909a_0    bioconda
bioconductor-singlecellexperiment 1.8.0                     r36_0    bioconda
bioconductor-summarizedexperiment 1.16.0                    r36_0    bioconda
bioconductor-xvector      0.26.0            r36h516909a_0    bioconda
bioconductor-zlibbioc     1.32.0            r36h516909a_0    bioconda
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
cnv_facets                0.16.0          py38r36h4b26f60_1    bioconda
curl                      7.68.0               hf8cf82a_0    conda-forge
expat                     2.6.3                h5888daf_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gcc_impl_linux-64         7.5.0               habd7529_20    conda-forge
gcc_linux-64              7.5.0               h47867f9_33    conda-forge
gettext                   0.22.5               he02047a_3    conda-forge
gettext-tools             0.22.5               he02047a_3    conda-forge
gfortran_impl_linux-64    7.5.0               h56cb351_20    conda-forge
gfortran_linux-64         7.5.0               h78c8a43_33    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gxx_impl_linux-64         7.5.0               hd0bb8aa_20    conda-forge
gxx_linux-64              7.5.0               h555fc39_33    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
htslib                    1.9                  h244ad75_9    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   3.10.0              h4a8ded7_16    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libasprintf               0.22.5               he8f35ee_3    conda-forge
libasprintf-devel         0.22.5               he8f35ee_3    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libcblas                  3.9.0           23_linux64_openblas    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libdeflate                1.21                 h4bc722e_0    conda-forge
libedit                   3.1.20191231         h46ee950_2    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-devel_linux-64     7.5.0               hda03d7c_20    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgettextpo              0.22.5               he02047a_3    conda-forge
libgettextpo-devel        0.22.5               he02047a_3    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-devel_linux-64  7.5.0               hb016644_20    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libtiff                   4.2.0                hf544144_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hb9d3cd8_1    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
make                      4.4.1                hb9d3cd8_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
r-acidbase                0.1.9                     r36_0    bioconda
r-assertthat              0.2.1             r36h6115d3f_2    conda-forge
r-backports               1.2.1             r36hcfec24a_0    conda-forge
r-base                    3.6.2                h3a67422_0    conda-forge
r-bh                      1.75.0_0          r36hc72bb7e_0    conda-forge
r-bioverbs                0.2.13                    r36_0    bioconda
r-bitops                  1.0_7             r36hcfec24a_0    conda-forge
r-brio                    0.3.17                    r36_0    bioconda
r-callr                   3.7.0             r36hc72bb7e_0    conda-forge
r-cellranger              1.1.0           r36h6115d3f_1003    conda-forge
r-cli                     2.5.0             r36hc72bb7e_0    conda-forge
r-clipr                   0.7.1             r36h142f84f_0    conda-forge
r-colorspace              2.0_1             r36hcfec24a_0    conda-forge
r-cpp11                   0.2.7             r36hc72bb7e_0    conda-forge
r-crayon                  1.4.1             r36hc72bb7e_0    conda-forge
r-curl                    4.3.1             r36hcfec24a_0    conda-forge
r-data.table              1.14.0            r36hcfec24a_0    conda-forge
r-desc                    1.3.0             r36hc72bb7e_0    conda-forge
r-diffobj                 0.3.4             r36hcfec24a_0    conda-forge
r-digest                  0.6.27            r36h03ef668_0    conda-forge
r-ellipsis                0.3.2             r36hcfec24a_0    conda-forge
r-evaluate                0.14              r36h6115d3f_2    conda-forge
r-fansi                   0.4.2             r36hcfec24a_0    conda-forge
r-farver                  2.1.0             r36h03ef668_0    conda-forge
r-forcats                 0.5.1             r36hc72bb7e_0    conda-forge
r-foreign                 0.8_76            r36hcdcec82_1    conda-forge
r-formatr                 1.9               r36hc72bb7e_0    conda-forge
r-futile.logger           1.4.3           r36h6115d3f_1003    conda-forge
r-futile.options          1.0.1           r36h6115d3f_1002    conda-forge
r-gdata                   2.18.0          r36h6115d3f_1003    conda-forge
r-ggplot2                 3.3.3             r36hc72bb7e_0    conda-forge
r-glue                    1.4.2             r36hcfec24a_0    conda-forge
r-goalie                  0.4.4                     r36_0    bioconda
r-gridextra               2.3             r36h6115d3f_1003    conda-forge
r-gtable                  0.3.0             r36h6115d3f_3    conda-forge
r-gtools                  3.8.2             r36hcdcec82_1    conda-forge
r-haven                   2.4.1             r36h2713e49_0    conda-forge
r-hms                     1.1.0             r36hc72bb7e_0    conda-forge
r-isoband                 0.2.4             r36h03ef668_0    conda-forge
r-jsonlite                1.7.2             r36hcfec24a_0    conda-forge
r-labeling                0.4.2             r36h142f84f_0    conda-forge
r-lambda.r                1.2.4             r36h6115d3f_1    conda-forge
r-lattice                 0.20_44           r36hcfec24a_0    conda-forge
r-lifecycle               1.0.0             r36hc72bb7e_0    conda-forge
r-magrittr                2.0.1             r36hcfec24a_1    conda-forge
r-mass                    7.3_54            r36hcfec24a_0    conda-forge
r-matrix                  1.3_3             r36he454529_0    conda-forge
r-matrixstats             0.58.0            r36hcfec24a_0    conda-forge
r-mgcv                    1.8_35            r36he454529_0    conda-forge
r-munsell                 0.5.0           r36h6115d3f_1003    conda-forge
r-nlme                    3.1_152           r36h859d828_0    conda-forge
r-openxlsx                4.2.3             r36h1b71b39_0    conda-forge
r-pillar                  1.6.1             r36hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_1    conda-forge
r-pkgload                 1.2.1             r36h03ef668_0    conda-forge
r-praise                  1.0.0           r36h6115d3f_1004    conda-forge
r-prettyunits             1.1.1             r36h6115d3f_1    conda-forge
r-processx                3.5.2             r36hcfec24a_0    conda-forge
r-progress                1.2.2             r36h6115d3f_2    conda-forge
r-ps                      1.6.0             r36hcfec24a_0    conda-forge
r-purrr                   0.3.4             r36hcfec24a_1    conda-forge
r-r.methodss3             1.8.1             r36h6115d3f_0    conda-forge
r-r.oo                    1.24.0            r36h6115d3f_0    conda-forge
r-r.utils                 2.10.1            r36h6115d3f_0    conda-forge
r-r6                      2.5.0             r36hc72bb7e_0    conda-forge
r-rcolorbrewer            1.1_2           r36h6115d3f_1003    conda-forge
r-rcpp                    1.0.6             r36h03ef668_0    conda-forge
r-rcurl                   1.98_1.2          r36hcdcec82_0    conda-forge
r-readr                   1.4.0             r36h1b71b39_0    conda-forge
r-readxl                  1.3.1             r36hde08347_4    conda-forge
r-rematch                 1.0.1           r36h6115d3f_1003    conda-forge
r-rematch2                2.1.2             r36h6115d3f_1    conda-forge
r-rio                     0.5.26            r36hc72bb7e_0    conda-forge
r-rlang                   0.4.11            r36hcfec24a_0    conda-forge
r-rprojroot               2.0.2             r36hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r36hc72bb7e_0    conda-forge
r-scales                  1.1.1             r36h6115d3f_0    conda-forge
r-snow                    0.4_3           r36h6115d3f_1002    conda-forge
r-stringi                 1.4.6             r36h0e574ca_2    conda-forge
r-stringr                 1.4.0             r36h6115d3f_2    conda-forge
r-testthat                3.0.2             r36h03ef668_0    conda-forge
r-tibble                  3.1.2             r36hcfec24a_0    conda-forge
r-tidyselect              1.1.1             r36hc72bb7e_0    conda-forge
r-transformer             0.2.12                    r36_0    bioconda
r-utf8                    1.2.1             r36hcfec24a_0    conda-forge
r-vctrs                   0.3.8             r36hcfec24a_1    conda-forge
r-viridislite             0.4.0             r36hc72bb7e_0    conda-forge
r-waldo                   0.2.5             r36hc72bb7e_0    conda-forge
r-withr                   2.4.2             r36hc72bb7e_0    conda-forge
r-xml                     3.99_0.3          r36hcdcec82_1    conda-forge
r-yaml                    2.2.1             r36hcfec24a_1    conda-forge
r-zip                     2.1.1             r36hcfec24a_0    conda-forge
readline                  8.0                  h46ee950_1    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
sed                       4.8                  he412f7d_0    conda-forge
setuptools                73.0.1             pyhd8ed1ab_0    conda-forge
snp-pileup                0.5.14               ha52163a_2    bioconda
sqlite                    3.40.1               h5082296_0  
sysroot_linux-64          2.17                h4a8ded7_16    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tktable                   2.10                 h8bc8fbc_6    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by danielt86** [comment]
Hi, sorry for late response,
Here is my mamba list:

# packages in environment at /mnt2/fscratch/users/oncoh_011_ibima/dtello/conda_env/cnv_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   h69a702a_16    conda-forge
bcftools                  1.9                  ha228f0b_4    bioconda
binutils_impl_linux-64    2.39                 he00db2b_1    conda-forge
binutils_linux-64         2.39                h5fc0e48_13    conda-forge
bioconductor-biocgenerics 0.32.0                    r36_0    bioconda
bioconductor-biocparallel 1.20.0            r36he1b5a44_0    bioconda
bioconductor-biostrings   2.54.0            r36h516909a_0    bioconda
bioconductor-genomeinfodb 1.22.0                    r36_0    bioconda
bioconductor-genomeinfodbdata 1.2.2                     r36_0    bioconda
bioconductor-genomicranges 1.38.0            r36h516909a_0    bioconda
bioconductor-iranges      2.20.0            r36h516909a_0    bioconda
bioconductor-rhtslib      1.18.0            r36hdb70ac9_1    bioconda
bioconductor-rsamtools    2.2.0             r36he1b5a44_0    bioconda
bioconductor-s4vectors    0.24.0            r36h516909a_0    bioconda
bioconductor-xvector      0.26.0            r36h516909a_0    bioconda
bioconductor-zlibbioc     1.32.0            r36h516909a_0    bioconda
bwidget                   1.9.16               h9eba36c_0  
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.33.1               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
cnv_facets                0.16.0          py38r36h4b26f60_1    bioconda
curl                      7.86.0               h2283fc2_1    conda-forge
expat                     2.6.3                h5888daf_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gcc_impl_linux-64         9.5.0               h99780fb_19    conda-forge
gcc_linux-64              9.5.0               h4258300_13    conda-forge
gfortran_impl_linux-64    9.5.0               hf1096a2_19    conda-forge
gfortran_linux-64         9.5.0               hdb51d14_13    conda-forge
graphite2                 1.3.14               h295c915_1  
gsl                       2.6                  he838d99_2    conda-forge
gxx_impl_linux-64         9.5.0               h99780fb_19    conda-forge
gxx_linux-64              9.5.0               h43f449f_13    conda-forge
harfbuzz                  3.1.1                h83ec7ef_0    conda-forge
htslib                    1.9                  ha228f0b_7    bioconda
icu                       68.2                 h9c3ff4c_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
kernel-headers_linux-64   3.10.0              h4a8ded7_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libcblas                  3.9.0           23_linux64_openblas    conda-forge
libcurl                   7.86.0               h2283fc2_1    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-devel_linux-64     9.5.0               h0a57e50_19    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libglib                   2.80.2               hf974151_0    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsanitizer              9.5.0               h2f262e1_19    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-devel_linux-64  9.5.0               h0a57e50_19    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libtiff                   4.2.0                hf544144_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hb9d3cd8_1    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
make                      4.4.1                hb9d3cd8_1    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
pango                     1.48.10              h54213e6_2    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.8.19          hd12c33a_0_cpython    conda-forge
r-assertthat              0.2.1             r36h6115d3f_2    conda-forge
r-backports               1.2.1             r36hcfec24a_0    conda-forge
r-base                    3.6.3                hbcea092_8    conda-forge
r-bh                      1.75.0_0          r36hc72bb7e_0    conda-forge
r-bitops                  1.0_7             r36hcfec24a_0    conda-forge
r-brio                    1.1.2             r36hcfec24a_0    conda-forge
r-callr                   3.7.0             r36hc72bb7e_0    conda-forge
r-cli                     2.5.0             r36hc72bb7e_0    conda-forge
r-colorspace              2.0_1             r36hcfec24a_0    conda-forge
r-crayon                  1.4.1             r36hc72bb7e_0    conda-forge
r-data.table              1.14.0            r36hcfec24a_0    conda-forge
r-desc                    1.3.0             r36hc72bb7e_0    conda-forge
r-diffobj                 0.3.4             r36hcfec24a_0    conda-forge
r-digest                  0.6.27            r36h03ef668_0    conda-forge
r-ellipsis                0.3.2             r36hcfec24a_0    conda-forge
r-evaluate                0.14              r36h6115d3f_2    conda-forge
r-fansi                   0.4.2             r36hcfec24a_0    conda-forge
r-farver                  2.1.0             r36h03ef668_0    conda-forge
r-formatr                 1.9               r36hc72bb7e_0    conda-forge
r-futile.logger           1.4.3           r36h6115d3f_1003    conda-forge
r-futile.options          1.0.1           r36h6115d3f_1002    conda-forge
r-ggplot2                 3.3.3             r36hc72bb7e_0    conda-forge
r-glue                    1.4.2             r36hcfec24a_0    conda-forge
r-gridextra               2.3             r36h6115d3f_1003    conda-forge
r-gtable                  0.3.0             r36h6115d3f_3    conda-forge
r-isoband                 0.2.4             r36h03ef668_0    conda-forge
r-jsonlite                1.7.2             r36hcfec24a_0    conda-forge
r-labeling                0.4.2             r36h142f84f_0    conda-forge
r-lambda.r                1.2.4             r36h6115d3f_1    conda-forge
r-lattice                 0.20_44           r36hcfec24a_0    conda-forge
r-lifecycle               1.0.0             r36hc72bb7e_0    conda-forge
r-magrittr                2.0.1             r36hcfec24a_1    conda-forge
r-mass                    7.3_54            r36hcfec24a_0    conda-forge
r-matrix                  1.3_3             r36he454529_0    conda-forge
r-mgcv                    1.8_35            r36he454529_0    conda-forge
r-munsell                 0.5.0           r36h6115d3f_1003    conda-forge
r-nlme                    3.1_152           r36h859d828_0    conda-forge
r-pillar                  1.6.1             r36hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_1    conda-forge
r-pkgload                 1.2.1             r36h03ef668_0    conda-forge
r-praise                  1.0.0           r36h6115d3f_1004    conda-forge
r-processx                3.5.2             r36hcfec24a_0    conda-forge
r-ps                      1.6.0             r36hcfec24a_0    conda-forge
r-r6                      2.5.0             r36hc72bb7e_0    conda-forge
r-rcolorbrewer            1.1_2           r36h6115d3f_1003    conda-forge
r-rcpp                    1.0.6             r36h03ef668_0    conda-forge
r-rcurl                   1.98_1.3          r36hcfec24a_0    conda-forge
r-rematch2                2.1.2             r36h6115d3f_1    conda-forge
r-rlang                   0.4.11            r36hcfec24a_0    conda-forge
r-rprojroot               2.0.2             r36hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r36hc72bb7e_0    conda-forge
r-scales                  1.1.1             r36h6115d3f_0    conda-forge
r-snow                    0.4_3           r36h6115d3f_1002    conda-forge
r-testthat                3.0.2             r36h03ef668_0    conda-forge
r-tibble                  3.1.2             r36hcfec24a_0    conda-forge
r-utf8                    1.2.1             r36hcfec24a_0    conda-forge
r-vctrs                   0.3.8             r36hcfec24a_1    conda-forge
r-viridislite             0.4.0             r36hc72bb7e_0    conda-forge
r-waldo                   0.2.5             r36hc72bb7e_0    conda-forge
r-withr                   2.4.2             r36hc72bb7e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
samtools                  1.6                 hc3601fc_10    bioconda
sed                       4.8                  he412f7d_0    conda-forge
setuptools                73.0.1             pyhd8ed1ab_0    conda-forge
snp-pileup                0.5.14               ha52163a_2    bioconda
sysroot_linux-64          2.17                h4a8ded7_16    conda-forge
tk                        8.6.14               h39e8969_0  
tktable                   2.10                 h8bc8fbc_6    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge


Now the data.table issue appears to be gone, but now I do get another issue:
Error: This is R 3.6.3, package ‘GenomeInfoDb’ needs >= 4.0.0

I tried installing it manually as well:
mamba install --freeze-installed -n cnv_env 'bioconductor-genomeinfodb=1.22.0'
However it says 'All requested packages already installed'

So not sure what is going on. Could it be a problem of my hpc cluster somehow? 

Thanks!

**Comment by dariober** [comment]
Sorry about the trouble. I should really revise the installation of cnv_facets and here's a start doing that. Can you try this:

* Setup a (fresh) mamba environment and add required packages. Some dependencies here are only relevant for testing. The name of the env (`cnv_facets` here) is your choice.

```
mamba create -n cnv_facets
mamba activate cnv_facets

mamba install 'r-facets=0.5.14' 'r-devtools' 'bioconductor-rsamtools' 'r-data.table' 'r-ggplot2' 'r-gridExtra' 'r-argparse' 'r-testthat' 'r-covr' 'samtools' 'bcftools' 'snp-pileup' 'vcf-validator'

## Match facets package to the version on the bioconda recipe (optional?)
Rscript -e 'devtools::install_github("mskcc/facets", ref = "434b5ce")'
```

* Get `cnv_facets.R` script and put it on the env path:

```
git clone https://github.com/dariober/cnv_facets.git
cd cnv_facets
chmod a+x bin/cnv_facets.R
cp bin/cnv_facets.R $CONDA_PREFIX/bin
```

* Optional: Run tests:

```
cd test/
Rscript testthat.R
python3 test_cnv_facets.py
```

**Comment by danielt86** [comment]
Hi there, just a quick update on my part. In the end I managed to make it work. I am not entirely sure what was going on, but probably something related to the HPC cluster I am currently using. In the end I removed everything R related from my user and started from a clean cnv_facets intallation. Now it works just fine. 

Thank you!

**Comment by gaitat** [comment]
@danielt86 Can you please include here the installation command you used?

**Comment by danielt86** [comment]
@gaitat Sure, I just followed the recommended ones and it worked. Again, this was after removing the R directory installed in my home (outside any environment). I figured this was causing the issues, since I probably accidentally installed some R packages related to another tool outside its proper environment (i.e., I forgot to activate the environment first). 

Commands used:
mamba create --name cnv_analysis cnv_facets
source activate cnv_analysis
mamba install -c bioconda -c conda-forge cnv_facets


Hope this helps.

**Comment by dariober** [comment]
@danielt86 

> i.e., I forgot to activate the environment first

Thanks for the update. I'm going to close the issue unless you have other questions. By the way, `source activate` is a pretty old way of activating an environment. Better to use:

```
mamba activate cnv_analysis
```

**Comment by danielt86** [comment]
@dariober All good now, so feel free to close it. Much appreciated. 
Yeah I know I can use mamba activate, but in the university's cluster the shell is not properly configured for it, so I am stuck using source activate (I get a warning and the environment does not activate unless I use source). Thanks anyways!
