### ISSUE TITLE
can this be used for tumor only mode?

### ISSUE THREAD

**Issue by kobejamescurry** [dariober/cnv_facets#7]
you are really a very kind person to make FACETS to be so easy to use. I want to ask you some questions for help. I hope you can help me when you are not that busy.

Q1: Due to my low ability, I think cnv_facets can not be used for tumor only mode(means there is no normal sample)

Q2:  A VCF file of common, polymorphic SNPs. For human samples, a good source is the dbSNP file common_all.vcf.gz. See also NCBI human variation sets in VCF Format.
there are so many file in GRCH37, is the files in red rectangle that I need to download
![image](https://user-images.githubusercontent.com/46668881/52616783-a2c0ce80-2ed4-11e9-9783-6cedbee55927.png)

Q3: I guess you must have a well founded knowledge of CNV, can you tell me how to find the LOH in cnv_facets results? and there is a new tool lohhla to specific to detect LOH in hla, and FACETS has beed cited in a science paper (Patient HLA class I genotype influences cancer response to
checkpoint blockade immunotherapy). do you think FACETS is accurate enough to detect LOH?

Thanks a lot.

**Comment by dariober** [comment]
Hi- glad you found cnv_facets useful!

> Q1: I think cnv_facets can not be used for tumor only mode(means there is no normal sample)

No, you cannot run only the tumour. However, you could use an unmatched normal sample and use the flag the `--unmatched/-u`. I think major CNVs should be picked up in this way.

> Q2: A VCF file of common, polymorphic SNPs. For human samples, a good source is the dbSNP file common_all.vcf.gz. See also NCBI human variation sets in VCF Format.
there are so many file in GRCH37, is the files in red rectangle that I need to download

I don't think clinvar is particularly good source in this case as you want polymorphic SNPs, not just those with clinical relevance. For dbSNPs download you could use ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/common_all_20180423.vcf.gz
As always, make sure the chromosome naming between VCF and BAM files is consistent i.e. chr1 vs chr2 ... vs 1, 2, ... If your bam files have chromosomes with prefix 'chr' use instead ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/GATK/common_all_20180423.vcf.gz 

> Q3: I guess you must have a well founded knowledge of CNV, can you tell me how to find the LOH in cnv_facets results? and there is a new tool lohhla to specific to detect LOH in hla, and FACETS has beed cited in a science paper (Patient HLA class I genotype influences cancer response to
checkpoint blockade immunotherapy). do you think FACETS is accurate enough to detect LOH?

In all honesty, I'm not *that* familiar with CNVs. The real engine under cnv_facets is https://github.com/mskcc/facets. My contribution has been to write a convenient wrapper for my analysis. In fact, questions specific to CNV calling using facets, like this one, may be better sent to https://github.com/mskcc/facets (if in doubt, send it to both, personally I don't mind).

**Comment by kobejamescurry** [comment]
@dariober, thanks for your kind and professional answer. 
I found your this great cnv_facets  when read issues in  the mskcc facets.
so you think we should choose common_all_20180423.vcf.gz for GRCH37.

**Comment by dariober** [comment]
Yes, I think common_all_20180423.vcf.gz is a good option but don't take my word for granted!
